---
- name: "Manage Docker as non-root user"
  shell: |
    sudo chmod 666 /var/run/docker.sock
  args:
    warn: false
- name: "Fetch Coder repository"
  shell: |
    git clone https://github.com/coder/coder.git
  args:
    warn: false
- name: "Copy Docker Compose configuration file"
  copy:
    src: docker-compose-coder.yaml
    dest: ./coder/docker-compose-coder.yaml
- name: "Install Coder as Docker Compose instance"
  shell: |
    cd coder
    docker compose -f docker-compose-coder.yaml up -d
  environment:
    CODER_ACCESS_URL: "https://{{ CODER_ACCESS_URL }}"
    CODER_WILDCARD_ACCESS_URL: "{{ CODER_WILDCARD_ACCESS_URL }}"
    CODER_OIDC_ISSUER_URL: "{{ CODER_OIDC_ISSUER_URL }}"
    CODER_OIDC_CLIENT_ID: "{{ CODER_OIDC_CLIENT_ID }}"
    CODER_OIDC_CLIENT_SECRET: "{{ CODER_OIDC_CLIENT_SECRET }}"
    CODER_EXPERIMENTAL: "{{ CODER_EXPERIMENTAL }}"
  args:
    warn: false
- name: Make sure service has time to start
  pause:
    seconds: 10
- name: "Configure first user"
  shell: |
    docker exec -it coder-coder-1 sh -c "CODER_FIRST_USER_USERNAME={{ CODER_FIRST_USER_USERNAME }} CODER_FIRST_USER_EMAIL={{ CODER_FIRST_USER_EMAIL }} CODER_FIRST_USER_PASSWORD={{ CODER_FIRST_USER_PASSWORD }} CODER_FIRST_USER_TRIAL={{ CODER_FIRST_USER_TRIAL }} coder login {{ CODER_ACCESS_URL }}"
  args:
    warn: false